project:
  type: website
  output-dir: docs
  resources:
    - libs/
    - img/
    - materials/
    - articles/
    - slides/libs/
  render:
    - index.qmd
    - slides/

website:
  title: "Literasi Data dan Penulisan Ilmiah"
  repo-url: https://github.com/rameliaz/literasi-data
  repo-branch: master
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - href: https://rameliaz.github.io/
        icon: house
        text: "oleh Rizqy Amelia Zein"
      - icon: envelope
        href: "mailto:amelia.zein@psikologi.unair.ac.id"
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/rameliaz/literasi-data
          - text: "Report Issues"
            href: https://github.com/rameliaz/literasi-data/issues
      - icon: house-heart
        url: https://rameliaz.github.io/
  sidebar:
    style: docked
    contents:
      - text: "Beranda"
        href: index.qmd
      - section: "Materi"
        contents:
          - text: "1. Pendahuluan: Literasi Data dalam Psikologi"
            href: slides/pertemuan1.html
          - text: "2. Bekerja dengan Data Tabular"
            href: slides/pertemuan2.html
          - text: "3. Menemukan dan Memanfaatkan Data Terbuka"
            href: slides/pertemuan3.html
          - text: "4. Praktik Verifikasi dan Pembersihan Data"
            href: slides/pertemuan4.html
          - text: "5. Merencanakan Analisis Data"
            href: slides/pertemuan5.html
          - text: "6. Praktik Analisis Data Sederhana"
            href: slides/pertemuan6.html
          - text: "7. Menyajikan Data"
            href: slides/pertemuan7.html
      - section: "Dataset"
        contents:
          - text: "Dataset IPIP"
            href: data/data.csv
          - text: "Kamus Data"
            href: data/codebook.txt
          - text: "Dataset Kotor Pertemuan 4"
            href: data/pertemuan4_dataset_kotor.csv
      - section: "Mentoring"
        contents:
          - text: "*Outline Narrative Review*"
            href: https://docs.google.com/document/d/1JUtv6JsyaOPtBVC79j2Dk9bafFV1XEnH/edit?usp=sharing&ouid=100126014993390956583&rtpof=true&sd=true
          - text: "Lembar Umpan Balik (untuk Mentor)"
            href: https://docs.google.com/document/d/15S3NJ51ZW24o0pNdNt_tIOebuG7Z64ki/edit?usp=sharing&ouid=100126014993390956583&rtpof=true&sd=true
  search:
    location: navbar
    type: overlay
  page-footer:
      left: "&#169; 2026 Rizqy Amelia Zein"
      right: "Magister Psikologi, Universitas Airlangga"
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-float: true
    toc-depth: 3
    df-print: paged
    highlight-style: github
